;;; Automatically generated by ‘recentf’ on Sun Oct  9 19:38:21 2022.

(setq recentf-list
      '(
        "/home/eric/.config/emacs/config.org"
        "/home/eric/Storage/Org/elfeed.org"
        "/home/eric/.config/emacs/elpa/evil-20221006.2227/evil-common.el"
        "/home/eric/.config/emacs/recentf"
        "/home/eric/.config/emacs/init.el"
        "/home/eric/Documents/test.R"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
